 name: CropsTop
 version: 1.0.0
 description: Display who has broken the most crops
 author: HarleySwtfus
 main: me.harley.cropstop.CropsTop
 
 commands:
   cropstop:
    aliases: [crops, canetop, topcrops]
    description: Main command
    usage: Incorrect usage of command! Are you using the right version?